-- Utility Script for helper functions etc.
ScriptHost:LoadScript("scripts/utils.lua")

Tracker:AddItems("items/items.json")
Tracker:AddMaps("maps/maps.json")

Tracker:AddLocations("locations/logic/general_logic.json")
Tracker:AddLocations("locations/games/01-mancala.json")
Tracker:AddLocations("locations/games/02-dotsandboxes.json")
Tracker:AddLocations("locations/games/03-yachtdice.json")
Tracker:AddLocations("locations/games/04-fourinarow.json")
Tracker:AddLocations("locations/games/05-hitandblow.json")
Tracker:AddLocations("locations/games/06-ninemensmorris.json")
Tracker:AddLocations("locations/games/07-hex.json")
Tracker:AddLocations("locations/games/08-checkers.json")
Tracker:AddLocations("locations/games/09-hareandhounds.json")
Tracker:AddLocations("locations/games/10-gomoku.json")
Tracker:AddLocations("locations/games/11-dominoes.json")
Tracker:AddLocations("locations/games/12-chinesecheckers.json")
Tracker:AddLocations("locations/games/13-ludo.json")
Tracker:AddLocations("locations/games/14-backgammon.json")
Tracker:AddLocations("locations/games/15-renegade.json")
Tracker:AddLocations("locations/games/16-chess.json")
Tracker:AddLocations("locations/games/17-shogi.json")
Tracker:AddLocations("locations/games/18-minishogi.json")
Tracker:AddLocations("locations/games/19-hanafuda.json")
Tracker:AddLocations("locations/games/20-riichimahjong.json")
Tracker:AddLocations("locations/games/21-lastcard.json")
Tracker:AddLocations("locations/games/22-blackjack.json")
Tracker:AddLocations("locations/games/23-texasholdem.json")
Tracker:AddLocations("locations/games/24-president.json")
Tracker:AddLocations("locations/games/25-sevens.json")
Tracker:AddLocations("locations/games/26-speed.json")
Tracker:AddLocations("locations/games/27-matching.json")
Tracker:AddLocations("locations/games/28-war.json")
Tracker:AddLocations("locations/games/29-takoyaki.json")
Tracker:AddLocations("locations/games/30-pigstail.json")
Tracker:AddLocations("locations/games/31-golf.json")
Tracker:AddLocations("locations/games/32-billiards.json")
Tracker:AddLocations("locations/games/33-bowling.json")
Tracker:AddLocations("locations/games/34-darts.json")
Tracker:AddLocations("locations/games/35-carrom.json")
Tracker:AddLocations("locations/games/36-toytennis.json")
Tracker:AddLocations("locations/games/37-toysoccer.json")
Tracker:AddLocations("locations/games/38-toycurling.json")
Tracker:AddLocations("locations/games/39-toyboxing.json")
Tracker:AddLocations("locations/games/40-toybaseball.json")
Tracker:AddLocations("locations/games/41-airhockey.json")
Tracker:AddLocations("locations/games/42-slotcars.json")
Tracker:AddLocations("locations/games/43-fishing.json")
Tracker:AddLocations("locations/games/44-battletanks.json")
Tracker:AddLocations("locations/games/45-teamtanks.json")
Tracker:AddLocations("locations/games/46-shootinggallery.json")
Tracker:AddLocations("locations/games/47-6ballpuzzle.json")
Tracker:AddLocations("locations/games/48-slidingpuzzle.json")
Tracker:AddLocations("locations/games/49-mahjongsolitaire.json")
Tracker:AddLocations("locations/games/50-klondikesolitaire.json")
Tracker:AddLocations("locations/games/51-spidersolitaire.json")

Tracker:AddLayouts("layouts/items.json")
Tracker:AddLayouts("layouts/tracker.json")
Tracker:AddLayouts("layouts/broadcast.json")

if PopVersion and PopVersion >= "0.18.0" then
    ScriptHost:LoadScript("scripts/autotracking.lua")
end